#!/bin/bash

export TF_VAR_MAAS_API_URL=$MAAS_API_URL
export TF_VAR_MAAS_API_KEY=$MAAS_API_KEY

sed  "s/my_machine_name/$1/g"  main.tf > output.file
rm main.tf
mv output.file main.tf

terraform init
terraform plan

terraform apply -auto-approve

terraform show -json | python -m maasta 

ansible-playbook -i inventory.yaml -b playbook.yaml
